# Generated by Django 2.2 on 2024-08-07 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0002_remove_bookmodel_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='status',
            field=models.CharField(default='Disactive', max_length=20),
        ),
    ]
