# Generated by Django 2.2 on 2024-08-07 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0004_borrowmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrowModel',
        ),
    ]
