# Generated by Django 2.2 on 2024-08-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0006_borrowmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='genderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='gradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='studentmodel',
            name='phone',
        ),
    ]
