# Generated by Django 2.2 on 2024-08-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0007_auto_20240808_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentModel',
        ),
    ]
