# Generated by Django 2.2 on 2024-08-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0009_studentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='studentModel',
        ),
    ]
