# Generated by Django 2.2 on 2024-08-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0011_studentmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='borrowModel',
        ),
        migrations.DeleteModel(
            name='studentModel',
        ),
    ]
