# Generated by Django 2.2 on 2024-08-08 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0012_auto_20240808_1812'),
    ]

    operations = [
        migrations.CreateModel(
            name='borrowModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_name', models.CharField(max_length=100)),
                ('b_image', models.ImageField(upload_to='')),
                ('s_name', models.CharField(max_length=100)),
                ('s_image', models.ImageField(upload_to='')),
                ('s_id', models.IntegerField(default=None)),
                ('s_gender', models.CharField(max_length=20)),
                ('s_grade', models.CharField(max_length=20)),
                ('s_phone', models.IntegerField(max_length=30)),
                ('s_email', models.EmailField(max_length=254)),
                ('s_address', models.TextField(max_length=200)),
                ('status', models.CharField(default='Borrow', max_length=20)),
                ('deadline', models.DateField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='studentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField(default=None)),
                ('image', models.ImageField(upload_to='')),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField(max_length=30)),
                ('address', models.TextField(max_length=200)),
                ('status', models.CharField(default='Disactive', max_length=20)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('gender', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMS_app.genderModel')),
                ('grade', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='LMS_app.gradeModel')),
            ],
        ),
    ]
