# Generated by Django 2.2 on 2024-08-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0013_borrowmodel_studentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowmodel',
            name='s_phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
