# Generated by Django 2.2 on 2024-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LMS_app', '0014_auto_20240808_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='create_at',
            field=models.DateTimeField(default=None),
        ),
    ]
